language: python
branches:
  only:
    - v3
install:
  - pip install jinja2 Markdown
script:
  - python chiwanpark.py
  - bash deploy.sh
env:
  global:
    - secure: "fxjEsed50sNAbhekG010Ad7HIJPdWd9W6I+XN8Slavn2e3F3iWf/2Qr3ljZ1wfevJ07LNUzrBjCB5JX8ozdKa62KiZSYtFbg327kkyBgydMUTte6RkXcGpRdfselzP0CRLR0NlOsU9mbJ9lUsAh7Cvm4bGm2zlfrrTNNunUSIFo="