# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chiwan Park
author: Chiwan Park
email: chiwanpark@hotmail.com
baseurl: ""
url: "https://chiwanpark.com"

# Collections
collections:
  posts:
    output: false
  articles:
    output: true
    permalink: /:collection/:path.html

# Build settings
plugins:
  - jekyll-feed
  - jekyll-git_metadata
  - jekyll-asciidoc
  - jekyll-font-awesome-sass
font-awesome:
  assets: true
asciidoc: {}
asciidoctor:
  attributes:
    source-highlighter: highlightjs
feed:
  collections:
    articles:
      path: "/feed.xml"
    posts:
      path: "/feed-dummy.xml" # prevent create RSS feed from posts collection
sitemap: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
